#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//////////////////////////////////////////////////////////////////////////////////////
//READ ME
//////////////////////////////////////////////////////////////////////////////////////

//This code can track the left and right side of the tape
//Places the box at the end of the track (not at the split road)
//First turns ccw 75 degrees then 75 degrees cw (from 0) to attempt to locate the line
//Tracks the line until it reaches the specified encoder value, then drops the box





//////////////////////////////////////////////////////////////////////////////////////
//GLOBAL VARIABLES AND FUNCTIONS
//////////////////////////////////////////////////////////////////////////////////////

bool ifLineRight;
bool ifLineLeft;


void motorStop() {
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);
}

task main()
{
//////////////////////////////////////////////////////////////////////////////////////
//INITALIZE GYRO, ARM POSITION, AND COLOR SENSOR
//////////////////////////////////////////////////////////////////////////////////////
	resetGyro(gyroSensor);
	setMotorSpeed(armMotor, 20);
	wait1Msec(1000);
	setMotorSpeed(armMotor, 0);
  resetMotorEncoder(armMotor);

  //initalize color sensor
	if(getColorReflected(colorSensor) < 43)
		setMotorTarget(leftMotor, 1, 20);		//this fixes it appearantly
	setMotorTarget(rightMotor, 1, 20);
	waitUntilMotorStop(leftMotor);

////////////////////////////////////////////////////////////////////////////////////
//GRAB BOX
////////////////////////////////////////////////////////////////////////////////////

	if (getUSDistance(sonarSensor) < 15) {	//if there is a box in front, pick it up
		while(true) {
			setMotorSpeed(leftMotor, 20);
			setMotorSpeed(rightMotor, 20);

			if (getUSDistance(sonarSensor) < 10) {
					setMotorTarget(armMotor, -180, 20);	//lower arm
					waitUntilMotorStop(armMotor);

					setMotorTarget(rightMotor, getMotorEncoder(rightMotor)+180, 20);
					setMotorTarget(leftMotor, getMotorEncoder(leftMotor)+180, 20);
					waitUntilMotorStop(leftMotor);
					break;
			}
		}
	}
	else {		//otherwise drive foreward only
		setMotorTarget(rightMotor, getMotorEncoder(rightMotor)+180, 20);
		setMotorTarget(leftMotor, getMotorEncoder(leftMotor)+180, 20);
		waitUntilMotorStop(leftMotor);
	}

////////////////////////////////////////////////////////////////////////////////////
//FIND LINE
////////////////////////////////////////////////////////////////////////////////////

	while(getGyroDegrees(gyroSensor) > -75)
	{
		//turn ccw until we hit the line or we turn 75 degrees
		setMotorSpeed(leftMotor, -20);
		setMotorSpeed(rightMotor, 20);

		if(getColorReflected(colorSensor) < 43){
			ifLineRight = true;					//found the line on the right side
			setMotorSpeed(leftMotor, 0);
			setMotorSpeed(rightMotor, 0);
			break;
		}
	}

	if(ifLineRight == false){
		while(getGyroDegrees(gyroSensor) < 75)
		{
			//turn cw until we hit the line or turn 75 degrees in the other direction
			setMotorSpeed(leftMotor, 20);
			setMotorSpeed(rightMotor, -20);

			if(getColorReflected(colorSensor) < 43){
				ifLineLeft = true;					//found the line on the left side
				setMotorSpeed(leftMotor, 0);
				setMotorSpeed(rightMotor, 0);
				break;
			}

		}
	}

	if((ifLineRight == false) && (ifLineLeft == false) ){
		//didnt find any line
		while(getGyroDegrees(gyroSensor) > -1)
		{
			setMotorSpeed(leftMotor, -20);	//turn ccw until we go back to 0 degrees
			setMotorSpeed(rightMotor, 20);
		}
	}

/////////////////////////////////////////////////////////////////////////
//TRACK RIGHT SIZE OF TAPE
/////////////////////////////////////////////////////////////////////////
	if (ifLineRight == true) {
		while(getMotorEncoder(leftMotor) < 5300)
		{
			//displayTextLine("%d", getMotorEncoder(leftMotor));
			displayBigStringAt(77, 84,"%d", getMotorEncoder(leftMotor));			//display left motor encoder and
			displayBigStringAt(77, 40,"%d", getColorReflected(colorSensor));	//getColorReflected
			setMotorSpeed(leftMotor, 7);
			setMotorSpeed(rightMotor, 20);			//drift left

			while(getColorReflected(colorSensor) < 40){
				setMotorSpeed(leftMotor, 40);
				setMotorSpeed(rightMotor, 0);			//drift right
			}
		}

		motorStop();
		setMotorTarget(rightMotor, getMotorEncoder(rightMotor)+120, 20);	//drive foreward
		setMotorTarget(leftMotor, getMotorEncoder(leftMotor)+120, 20);
		waitUntilMotorStop(leftMotor);

		motorStop();
		setMotorTarget(armMotor, -20, 20);			//raise arm
		waitUntilMotorStop(armMotor);

		setMotorTarget(rightMotor, getMotorEncoder(rightMotor)-360, 20);	//drive back
		setMotorTarget(leftMotor, getMotorEncoder(leftMotor)-360, 20);
		waitUntilMotorStop(leftMotor);
		motorStop();


	}

/////////////////////////////////////////////////////////////////////////
//TRACK LEFT SIZE OF TAPE
/////////////////////////////////////////////////////////////////////////
	if (ifLineLeft == true) {
		while(getMotorEncoder(rightMotor) < 4550)
		{
			//displayTextLine("%d", getMotorEncoder(leftMotor));
			displayBigStringAt(77, 84,"%d", getMotorEncoder(rightMotor));			//display right motor encoder and
			displayBigStringAt(77, 40,"%d", getColorReflected(colorSensor));	//getColorReflected
			setMotorSpeed(rightMotor, 5);
			setMotorSpeed(leftMotor, 25);			//drift right


			while(getColorReflected(colorSensor) < 40){
				setMotorSpeed(rightMotor, 40);
				setMotorSpeed(leftMotor, 0);		//drift left
			}
		}

		motorStop();

		setMotorTarget(rightMotor, getMotorEncoder(rightMotor)-90, 20);		//turn cw a little bit
		setMotorTarget(leftMotor, getMotorEncoder(leftMotor)+90, 20);
		waitUntilMotorStop(leftMotor);

		motorStop();
		setMotorTarget(rightMotor, getMotorEncoder(rightMotor)+120, 20);		//drive foreward
		setMotorTarget(leftMotor, getMotorEncoder(leftMotor)+120, 20);
		waitUntilMotorStop(leftMotor);

		motorStop();
		setMotorTarget(armMotor, -20, 20);		//raise arm
		waitUntilMotorStop(armMotor);

		setMotorTarget(rightMotor, getMotorEncoder(rightMotor)-120, 20);		//drive back
		setMotorTarget(leftMotor, getMotorEncoder(leftMotor)-120, 20);
		waitUntilMotorStop(leftMotor);
		motorStop();


	}


}
