#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//////////////////////////////////////////////////////////////////////////////////////
//READ ME
//////////////////////////////////////////////////////////////////////////////////////

//This code is of modification of MainDelivery.c
//Places the box at the split road, and can track both sides of the line
//Displays "Delivery Complete" three times after it places the box




//////////////////////////////////////////////////////////////////////////////////////
//GLOBAL VARIABLES AND FUNCTIONS
//////////////////////////////////////////////////////////////////////////////////////

bool ifLineRight;
bool ifLineLeft;

void motorStop() {
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);
}

task main()
{
//////////////////////////////////////////////////////////////////////////////////////
//INITALIZE GYRO, ARM POSITION, AND COLOR SENSOR
//////////////////////////////////////////////////////////////////////////////////////
	resetGyro(gyroSensor);
	setMotorSpeed(armMotor, 20);
	wait1Msec(1000);
	setMotorSpeed(armMotor, 0);
  resetMotorEncoder(armMotor);

	//initalize color sensor
	if(getColorReflected(colorSensor) < 43)
		setMotorTarget(leftMotor, 1, 20);
	setMotorTarget(rightMotor, 1, 20);
	waitUntilMotorStop(leftMotor);

////////////////////////////////////////////////////////////////////////////////////
//GRAB BOX
////////////////////////////////////////////////////////////////////////////////////

	if (getUSDistance(sonarSensor) < 15) {		//if there is a box in front, pick it up
		while(true) {
			setMotorSpeed(leftMotor, 20);
			setMotorSpeed(rightMotor, 20);

			if (getUSDistance(sonarSensor) < 10) {
					setMotorTarget(armMotor, -180, 20);	//lower arm			//ADJUST THIS IN VIRTUAL WORLDS
					waitUntilMotorStop(armMotor);

					setMotorTarget(rightMotor, getMotorEncoder(rightMotor)+180, 20);
					setMotorTarget(leftMotor, getMotorEncoder(leftMotor)+180, 20);
					waitUntilMotorStop(leftMotor);
					break;
			}
		}
	}
	else {	//otherwise drive foreward only
		setMotorTarget(rightMotor, getMotorEncoder(rightMotor)+180, 20);
		setMotorTarget(leftMotor, getMotorEncoder(leftMotor)+180, 20);
		waitUntilMotorStop(leftMotor);
	}

////////////////////////////////////////////////////////////////////////////////////
//FIND LINE
////////////////////////////////////////////////////////////////////////////////////


	while(getGyroDegrees(gyroSensor) > -75)
	{
		//turn ccw until we hit the line or we turn 75 degrees
		setMotorSpeed(leftMotor, -20);
		setMotorSpeed(rightMotor, 20);

		if(getColorReflected(colorSensor) < 43){
			ifLineRight = true;			//found the line on the right side
			break;
		}

	}

	if(ifLineRight == false){
		while(getGyroDegrees(gyroSensor) < 75)
		{
			//turn cw until we hit the line or turn 75 degrees in the other direction
			setMotorSpeed(leftMotor, 20);
			setMotorSpeed(rightMotor, -20);

			if(getColorReflected(colorSensor) < 43){
				ifLineLeft = true;					//found the line on the left side
				setMotorSpeed(leftMotor, 0);
				setMotorSpeed(rightMotor, 0);
				break;
			}

		}
	}

	if((ifLineRight == false) && (ifLineLeft == false) ){
		//didnt find any line
		while(getGyroDegrees(gyroSensor) > -1)
		{
			setMotorSpeed(leftMotor, -20);		//turn ccw until we go back to 0 degrees
			setMotorSpeed(rightMotor, 20);
		}
	}

/////////////////////////////////////////////////////////////////////////
//TRACK RIGHT SIZE OF TAPE
/////////////////////////////////////////////////////////////////////////
	if (ifLineRight == true) {
		while(getMotorEncoder(leftMotor) < 3150)		//ADJUST THIS IN VIRTUAL WORLDS
		{
			//displayTextLine("%d", getMotorEncoder(leftMotor));
			//displayBigStringAt(77, 84,"%d", getMotorEncoder(leftMotor));
			//displayBigStringAt(77, 40,"%d", getColorReflected(colorSensor));
			//displayString(2,"%d", getMotorEncoder(leftMotor));
			setMotorSpeed(leftMotor, 7);			//drift left
			setMotorSpeed(rightMotor, 20);


			//if(getUSDistance(sonarSensor) < 10 && getUSDistance(sonarSensor) > 7){
			//		setMotorTarget(armMotor, -180, 20);
			//}

			while(getColorReflected(colorSensor) < 40){
				setMotorSpeed(leftMotor, 40);		//drift right
				setMotorSpeed(rightMotor, 0);
			}
		}


		motorStop();
		setMotorTarget(armMotor, -20, 20);	//raise arm
		waitUntilMotorStop(armMotor);

		setMotorTarget(rightMotor, getMotorEncoder(rightMotor)-360, 20);		//drive back
		setMotorTarget(leftMotor, getMotorEncoder(leftMotor)-360, 20);
		waitUntilMotorStop(leftMotor);
		motorStop();

		eraseDisplay();								//display "Delivery Complete" three times on the LCD
		for (int i = 0; i<3; i++ ){
			displayBigStringAt(77, 84,"Delivery Successful");
			wait1Msec(1000);
			eraseDisplay();
			wait1Msec(1000);
		}

	}
/////////////////////////////////////////////////////////////////////////
//TRACK LEFT SIZE OF TAPE
/////////////////////////////////////////////////////////////////////////
	if (ifLineLeft == true) {
		while(getMotorEncoder(rightMotor) < 3150)		//ADJUST THIS IN VIRTUAL WORLDS
		{
			//displayTextLine("%d", getMotorEncoder(leftMotor));
			//displayBigStringAt(77, 84,"%d", getMotorEncoder(rightMotor));
			//displayBigStringAt(77, 40,"%d", getColorReflected(colorSensor));
			//displayString(2,"%d", getMotorEncoder(leftMotor));
			setMotorSpeed(rightMotor, 0);
			setMotorSpeed(leftMotor, 20);		//drift right


			//if(getUSDistance(sonarSensor) < 10 && getUSDistance(sonarSensor) > 7){
			//	setMotorTarget(armMotor, -180, 20);
			//}

			while(getColorReflected(colorSensor) < 40){
				setMotorSpeed(rightMotor, 20);			//drift left
				setMotorSpeed(leftMotor, 0);
			}
		}

		motorStop();
		setMotorTarget(armMotor, -20, 20);		//raise arm
		waitUntilMotorStop(armMotor);

		setMotorTarget(rightMotor, getMotorEncoder(rightMotor)-360, 20);	//drive back
		setMotorTarget(leftMotor, getMotorEncoder(leftMotor)-360, 20);
		waitUntilMotorStop(leftMotor);
		motorStop();

		eraseDisplay();									//display "Delivery Complete" three times on the LCD
		for (int i = 0; i<3; i++ ){
			displayBigStringAt(77, 84,"Delivery Successful");
			wait1Msec(1000);
			eraseDisplay();
			wait1Msec(1000);
		}

	}


}
