#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////////////////////////////
//FUNCTIONS
//
//
//

//Convert binary number to decimal number
int bin2dec(int num){
	int dec = 0;
	int i = 0;
	while(num != 0){
		int rem = num % 10;
		num = num / 10;
		dec = rem * pow(2,i) + dec;
		++i;
	}
	return dec;
}

int concatenate(int a, int b)
{
  char s1[10];
  char s2[10];
  // Converting both the integers to string
  sprintf(s1, "%d", a);             //"1"
  sprintf(s2, "%d", b);             //"0"
  // combine/concatenate both strings
  strcat(s1, s2);                   //"1" + "0" = "10" = s1
 	//displayCenteredTextLine(2, s1);
  // Convert the combined/concatenated string into integer
  int c = atoi(s1);
  // return the integer value
  return c;
}

int concatenateDBL(int a, int b)
{
  char s1[10];
  char s2[10];
  // Converting both the integers to string
  sprintf(s1, "%02d", a);
  sprintf(s2, "%02d", b);
  // combine/concatenate both strings
  strcat(s1, s2);
 	//displayCenteredTextLine(2, s1);
  // Convert the combined/concatenated string into integer
  int c = atoi(s1);
  // return the integer value
  return c;
}

///////////////////////////////////////////////////////////////////////
//MAIN CODE
//
//
//

int TimeArray[4];
int binArray[4];
int i = 0;
int time = 0;

task main()
{
	//initalize color sensor
	if(getColorReflected(colorSensor) < 100){
		setMotorTarget(leftMotor, 1, 5);		//this fixes it appearantly
		setMotorTarget(rightMotor, 1, 5);
		waitUntilMotorStop(leftMotor);
		waitUntilMotorStop(rightMotor);
	}

	//clear datalog, and set motor speed to 100
	datalogClear();
	setMotorSpeed(leftMotor, 100);     //Motor speed can be set to 5 for bot to move slower
	setMotorSpeed(rightMotor, 100);    //Setting speed to 5 would require you to change TimeArray[i] = time/200 (divide by larger number)
																     //After changing saved time, you have to change the if statements on line 100 & 119
																		 // *if(TimeArray[i] < 1)* change 1 to different value depending on range of values saved in TimeArray
																		 //At speed 100, the values saved are either 0 or 2


	//True statement following main code of reading black and white bars
	while(true)
	{

		//checks that 4 black and white bars have been read by the robot
	  //if 4 iterations have been completed AND colour sensor reads white, loop is broken
		if( (i > 3) && (getColorReflected(colorSensor)>30)){
			setMotorSpeed(leftMotor, 0);
			setMotorSpeed(rightMotor, 0);
			break;
		}


		//bot follows set speed and doesnt add to datalog until it sees first black bar
		if(getColorReflected(colorSensor) < 20){

			//if bar is black, depending on its length, its value (0 or 1) is displayed on the bot display
			while (getColorReflected(colorSensor) <= 40){
				time++;
		 		TimeArray[i] = time/200;   //divide by 200 to display time in value close to seconds
				if (TimeArray[i] < 1){
				  displayCenteredBigTextLine(i*2, "0");
				}else{
					displayCenteredBigTextLine(i*2, "1");
				}
			}

			//if bar is white, time is reinitialized to 0
			//if loop has been iterated 3 times, it breaks out of the loop below
			while (getColorReflected(colorSensor) > 40){
				time = 0;
				if ( i > 2){
					break;
				}
			}
			i++;
		}
	}

	//TimeArray values are saved as binary values in binArray
	for(int j = 0; j<4 ; j++){
		if (TimeArray[j] < 1){
	  	binArray[j] = 0;
		}else{
			binArray[j] = 1;
		}
	}

	//concatenating all binary values to create plessy, binary, and decimal numbers
	int Ples1 = concatenate(binArray[0], binArray[1]);
	int Ples2 = concatenate(binArray[2], binArray[3]);
	int PlessyBin = concatenateDBL(Ples1, Ples2);

	int Bin1 = concatenate(binArray[3], binArray[2]);
	int Bin2 = concatenate(binArray[1], binArray[0]);
	int FullBin = concatenateDBL(Bin1, Bin2);
	int FullDec = bin2dec(FullBin);

	//display all values
	displayCenteredTextLine(10, "Plessy Value: %04d", PlessyBin);

	displayCenteredTextLine(12, "Binary Value: %04d", FullBin);

	displayCenteredTextLine(14, "Barcode Scanned Value: %d", FullDec);
	delay(10000);


}
