#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////////////////////////////
//FUNCTIONS
//
//
//

//Convert binary number to decimal number
int bin2dec(int num){
	int dec = 0;
	int i = 0;
	while(num != 0){
		int rem = num % 10;
		num = num / 10;
		dec = rem * pow(2,i) + dec;
		++i;
	}
	return dec;
}

int concatenate(int a, int b)
{
  char s1[10];
  char s2[10];
  // Converting both the integers to string
  sprintf(s1, "%d", a);             //"1"
  sprintf(s2, "%d", b);             //"0"
  // combine/concatenate both strings
  strcat(s1, s2);                   //"1" + "0" = "10" = s1
 	//displayCenteredTextLine(2, s1);
  // Convert the combined/concatenated string into integer
  int c = atoi(s1);
  // return the integer value
  return c;
}

int concatenateDBL(int a, int b)
{
  char s1[10];
  char s2[10];
  // Converting both the integers to string
  sprintf(s1, "%02d", a);
  sprintf(s2, "%02d", b);
  // combine/concatenate both strings
  strcat(s1, s2);
 	//displayCenteredTextLine(2, s1);
  // Convert the combined/concatenated string into integer
  int c = atoi(s1);
  // return the integer value
  return c;
}

///////////////////////////////////////////////////////////////////////
//MAIN CODE
//
//
//

//initialize global variables
int TimeArray[4];
int binArray[4];
int time = 0;

task main()
{
	//move bot out of start area
	setMotorTarget(leftMotor, 700, 20);
	setMotorTarget(rightMotor, 700, 20);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);

	//clear datalog, and set motor speed to 20
	datalogClear();
	setMotorSpeed(leftMotor, 20);
	setMotorSpeed(rightMotor, 20);

	//initialize local variable
	int i = 0;

	while(true)
	{

		//checks that 4 black and white bars have been read by the robot
	  //if 4 iterations have been completed AND colour sensor reads white, loop is broken
		if( (i > 3) && (getColorReflected(colorSensor)>70)){
			setMotorSpeed(leftMotor, 0);
			setMotorSpeed(rightMotor, 0);
			break;
		}


		if(getColorReflected(colorSensor) < 70){
			//if bar is black, depending on its length, its value (0 or 1) is displayed on the bot display
			while (getColorReflected(colorSensor) <= 70){
				time++;
				TimeArray[i] = time/2000;   //divide by 2000 to display time in value close to seconds
				if (TimeArray[i] < 900){
				  displayCenteredTextLine(i, "0");
				}else{
					displayCenteredTextLine(i, "1");
				}
			}

			//if bar is white, time is reinitialized to 0
			//if loop has been iterated 3 times, it breaks out of the loop below
			while (getColorReflected(colorSensor) > 70){
				time = 0;
				//add final iteration to make i=4 and end loop on next run in while loop
				if ( i > 2){
					break;
					i++;
				}
			}
			//iterate local variable
			i++;
		}
	}

	//TimeArray values are saved as binary values in binArray
	for(int j = 0; j<4 ; j++){
		if (TimeArray[j] < 700){
	  	binArray[j] = 0;
		}else{
			binArray[j] = 1;
		}
	}

	//concatenating all binary values to create plessy, binary, and decimal numbers
	int Ples1 = concatenate(binArray[0], binArray[1]);
	int Ples2 = concatenate(binArray[2], binArray[3]);
	int PlessyBin = concatenateDBL(Ples1, Ples2);

	int Bin1 = concatenate(binArray[3], binArray[2]);
	int Bin2 = concatenate(binArray[1], binArray[0]);
	int FullBin = concatenateDBL(Bin1, Bin2);
	int FullDec = bin2dec(FullBin);

	//display all values
	displayCenteredTextLine(5, "Plessy Value: %04d", PlessyBin);

	displayCenteredTextLine(6, "Binary Value: %04d", FullBin);

	displayCenteredTextLine(7, "Barcode Scanned Value: %d", FullDec);
	delay(10000);


}
