#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//Set global variable
int i = 0;
task main()
{

	//initalize color sensor
	if(getColorReflected(colorSensor) < 43)
		setMotorTarget(leftMotor, 1, 20);		//this fixes it appearantly
	setMotorTarget(rightMotor, 1, 20);
	waitUntilMotorStop(leftMotor);

	//clear datalog and set speed to 5
	datalogClear();
	setMotorSpeed(leftMotor, 5);
	setMotorSpeed(rightMotor, 5);

	while(true)
	{

		//checks that 4 black and white bars have been read by the robot
	  //if 4 iterations have been completed AND colour sensor reads white, loop is broken
		if( (i > 3) && (getColorReflected(colorSensor)>30)){
			setMotorSpeed(leftMotor, 0);
			setMotorSpeed(rightMotor, 0);
			break;
		}

		//start when black bar is detected
		if(getColorReflected(colorSensor) < 20){

				//while light reflected off black bar, save all values in datalog
				while (getColorReflected(colorSensor) <= 40){
					datalogDataGroupStart();
			  	datalogAddValue(0, getColorReflected(colorSensor));
			  	datalogDataGroupEnd();
			  	sleep(50);
				}
				//while light reflected off white bar, save all values in datalog
				while (getColorReflected(colorSensor) > 40){
					datalogDataGroupStart();
			  	datalogAddValue(0, getColorReflected(colorSensor));
			  	datalogDataGroupEnd();
			  	sleep(50);
			  	//if on last black bar, move forward for 25 iterations and save to datalog
					if ( i > 2){
						for(i = 0;i< 25;i++){
							datalogDataGroupStart();
					  	datalogAddValue(0, getColorReflected(colorSensor));
					  	datalogDataGroupEnd();
					  	sleep(50);

				 		}
						break;
					}
				}
				i++;
		}

	}
}
